# Copyright Jiaqi Liu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: "UI Code Style Checks"
# description: "Prettier & ESLint in a yarn-based project"

on:
    workflow_call:
        inputs:
            node_version:
                description: 'NodeJS    version, such as "16"'
                required: true

jobs:
    ui-code-style-job:
        name: Ui Code Style Job
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set node version to ${{ inputs.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ inputs.node-version }}
            - name: Install dependencies
              run: yarn install
              shell: bash
            - name: Code style check
              shell: bash
              run: yarn prettier . --check
            - name: ESLint
              run: yarn eslint .
              shell: bash
